// <auto-generated />
using es_agency_api.Domain;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace esagencyapi.Migrations
{
    [DbContext(typeof(EstateAgencyDbContext))]
    [Migration("20181224131440_FixedNameing")]
    partial class FixedNameing
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("es_agency_api.Domain.Auction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<double>("ActualPrice");

                    b.Property<int>("AuctionItemId");

                    b.Property<int>("BiddersCount");

                    b.Property<double>("StartingPrice");

                    b.Property<int>("WinningBidId");

                    b.Property<DateTime>("endTime");

                    b.Property<DateTime>("startTime");

                    b.HasKey("Id");

                    b.HasIndex("AuctionItemId")
                        .IsUnique();

                    b.ToTable("Auctions");
                });

            modelBuilder.Entity("es_agency_api.Domain.AuctionItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AuctionType");

                    b.Property<string>("Description");

                    b.Property<double>("Measurement");

                    b.Property<string>("PhotoUrl");

                    b.HasKey("Id");

                    b.ToTable("AuctionItems");
                });

            modelBuilder.Entity("es_agency_api.Domain.Bid", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AucitionId");

                    b.Property<DateTime>("BidDateTime");

                    b.Property<double>("Offer");

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.ToTable("Bids");
                });

            modelBuilder.Entity("es_agency_api.Domain.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email");

                    b.Property<string>("Name");

                    b.Property<string>("Password");

                    b.Property<string>("Surename");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("es_agency_api.Domain.Auction", b =>
                {
                    b.HasOne("es_agency_api.Domain.AuctionItem")
                        .WithOne("ItemAuction")
                        .HasForeignKey("es_agency_api.Domain.Auction", "AuctionItemId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
